INSERT INTO RECIPE VALUES (1,'Special fried rice','Rice, Egg, Soy sauce, ')
INSERT INTO RECIPE VALUES (2,'Spaghetti Bolognese','Beef,Tomato,Onion & Garlic,Bay leaves,Pasta')
INSERT INTO RECIPE VALUES (3,'Chicken Katsu','Chicken, Salt, Egg, Oil')
INSERT INTO RECIPE VALUES (4,'Pasta with salmon & peas','Salmon, Fusilli, Peas, Low fat cream, Butter')
INSERT INTO RECIPE VALUES (4,'Thai red curry','Coconut milk, Jasmine rice, Coconut milk, Red curry paste')